### ISSUE TITLE
Update Tailor to use ES6 

### ISSUE THREAD

**Issue by addi90** [zalando/tailor#102]
Even though NodeJS (along with --harmony flag in v4) provides a lot of ES6 features, the Tailor code doesn't use all of them. Update the code to refactor the Tailor code using ES6. E.g.

1. Add destructuring to files

```javascript
fragmentObj = Object.assign({}, { name: node.name, attributes: node.attribs});
```
to 

```javascript
const { name, attribs: attributes } = node;
fragmentObj = Object.assign({}, { name, attributes});
```

2. Use `() =>` to avoid some boilerplate
```javascript
const stripUrl = (fileUrl) => {
    return path.normalize(fileUrl.replace('file://', ''));
};
```

```javascript
const stripUrl = fileUrl => path.normalize(fileUrl.replace('file://', ''));
```

**Comment by vigneshshanmugam** [comment]
@addi90 Thanks for the idea and yes indeed there are even lots of places where all the features are not utilised.

It would be even cool if we can get https://github.com/babel/babel-preset-env to work and ship to 4.4.x and major versions.

**Comment by fokusferit** [comment]
btw. you guys maybe consider looking into https://github.com/lebab/lebab ? As it does the opposite turns ES5 code into ES6/ES7 it might be interesting or worth checking out. Maybe it could save some time doing replacements manually ?

**Comment by addi90** [comment]
@fokusferit Looks interesting. I will try it today to see if it is exhaustive in the ES5-ES6 conversion. Thanks a lot for sharing this

**Comment by dazld** [comment]
Node 4.x active LTS period is up until 2017-04-01, for reference.
