### ISSUE TITLE
Add a TOC to the Perfomance documentation page

### ISSUE THREAD

**Issue by jukey** [zalando/tailor#105]
- [ ] figure out if what tool/mechanism could be used to generate a TOC once content in a defined doc file changes
- [ ] Implement into [Performance.md](https://github.com/zalando/tailor/blob/master/docs/Performance.md)

**Comment by vigneshshanmugam** [comment]
@jukey TOC? Can you be more specific?

**Comment by jukey** [comment]
TOC = Table of content - a short index at the beginning of the page that allows to jump right to a chapter of choice.

**Comment by vigneshshanmugam** [comment]
@jukey Cool. Please go suggest some ideas if you have anything in mind. Also PR would be great :)

**Comment by vigneshshanmugam** [comment]
https://github.com/zalando/tailor#concepts .. thoughts?

**Comment by jukey** [comment]
This already a great starting point that makes it easy to find the stuff on the perfomance page. However I would like to investigate further if there is an easy way to create a toc for all the chapters of given md pages.

**Comment by vigneshshanmugam** [comment]
Please do send a PR with your thoughts.

**Comment by jukey** [comment]
There is a [github feature request](https://github.com/isaacs/github/issues/215) to add a mechanism to provide a automatically generated table of content to markdown pages.

As workaround a simple tool, called [TocDoc](http://doctoc.herokuapp.com/), exists that generates a toc for a given markdown URL. Unfortunately it seems the internal linking of chapters does not work (there is just a `(#)` added) but it's a good starting point.

Feels free to suggest a better solution if available.

**Comment by vigneshshanmugam** [comment]
Checked the PR #122 It looks good.. I dont have know of any alternative tool for creating contents.
