### ISSUE TITLE
How to forward query and path parameters?

### ISSUE THREAD

**Issue by JanRudert** [zalando/tailor#116]
Hi,

I'm trying to find a way to forward the query string (e.g. 'query=string' in http://host.com/some/123?query=string") to my fragment servers. 

I also try to find a solution for path parameters (e.g. '123' in above example) . I know that it's possible to replace the default implementation of fetch-template to not match the whole path name and that I can transform path parameters to query strings with skipper. But is there an easier / less intrusive way to achieve this?

Thanks a lot
Jan

**Comment by vigneshshanmugam** [comment]
@JanRudert As you mentioned, we use skipper in front of tailor and modify the path based on regex using the skipper filter. 

But you can also use a middleware in front of tailor and add the query params to the headers like this 
```js
http.createServer((req, res) => {
    //you can mutate the path and add new headers to request. 
   tailor.requestHandler(req, res);
});

```

**Comment by JanRudert** [comment]
@vigneshshanmugam thank you! I already played around with Tailor and injected an adapted version of the requestFragment function which adds path and query parameters to the fragment server request.

I still do not exactly get how Skipper can help me in the communication between tailor and the fragment servers. Skipper resides in front of tailor. So any request transformed by Skipper will hit Tailor anyway. And tailors default implementation will not push parameters onwards.

Would be great if you'd clarify this to me.

Thanks in advance
Jan

**Comment by vigneshshanmugam** [comment]
By using skipper filters we make sure the request path goes to the proper template url of tailor maintained by separate team. 
```
// before skipper
user request - www.zalando.de/cart

// after skipper filters
template name for tailor - /foldername/cart

// tailor 
Tailor is not aware of the end user URL instead it goes and fetches the templates from /foldername/cart which is modified by the skipper. 
```

As you mentioned, The default implementation does not forward the query params to fragment servers.

**Comment by jmaicher** [comment]
We have a similar setup, only that we do not use skipper but our own gateway, which, amongst other things, handles authentication. Given https://github.com/zalando/tailor/issues/97, we set certain headers in the gateway (e.g. X-User or X-Path), which are then forwarded to the fragment servers via customizing the `filterHeaders` function.

**Comment by rikkert** [comment]
Interesting, I made a hybrid solution now:
- apache as reverse proxy does not touch the URI so layout service gets the full original URI
- middleware removes prefix from req.url so templates will match as by default in tailor (template folder)
- fetchContext copies the original search params to the fragment src
- filterHeaders copies the original req headers and adds a header when a specific fragment needs it

**Comment by tomploem** [comment]
Hello @rikkert and @jmaicher ,

I am searching for a similar solution. Can someone maybe share a solution? This would help a lot!

**Comment by vigneshshanmugam** [comment]
@tomploem If you are not using any proxy infront of tailor, I would recommend this approach https://github.com/zalando/tailor/issues/116#issuecomment-276909610

You could then forward the custom headers you need through `filterHeaders` function as tailor [options](https://github.com/zalando/tailor#options)

Hope this helps. Please reopen it if you guys need any help.

**Comment by hpoom** [comment]
I am keen to know the answer to this too. How can I pass on query string from the call to tailor onto the calls to the fragment servers. Issue #129 asks the same thing but was closed.

I can see from above that I can put the query string into the headers, but as my fragment server also serves another service that is not tailor I don't really want to cater for headers and copy those back into the query at the start of the code in the fragment server.

I have a hacked version of Tailor that does pass on the query params but would be good to investigate if I can pass on the query params with Tailor without changing the code, maybe a config param. Something like: `<fragment src="http://footer.domain.com" chainquery></fragment>`

**Comment by hpoom** [comment]
@rikkert I would be interested to see your code branch that does `fetchContext copies the original search params to the fragment src`
