### ISSUE TITLE
Is maintainers file current?

### ISSUE THREAD

**Issue by LappleApple** [zalando/tailor#119]
Wondering if Andrey K's still contributing; also Aditya now seems to be doing a lot of work but you guys would decide if he's "maintainer" status.

**Comment by vigneshshanmugam** [comment]
Andrey was the author and currently, he is also reviewing some of the PR's. Regarding adding new people to the maintainer status, We would wait for sometime and decide later.

**Comment by LappleApple** [comment]
Sounds good, @vigneshshanmugam. Thanks!
