### ISSUE TITLE
How to handle ajax calls?

### ISSUE THREAD

**Issue by smilingleo** [zalando/tailor#132]
I'm trying to make tailor work with an Angular2 app, tailor can load the page, but the Ajax call fails since the page is rendered by tailor and the Ajax call will go to tailor's domain but not the Angular2 backend server.

One way is to replace the API URI to full path but which will require cross origin resource sharing (CORS) supported.

Another way I'm thinking is to have tailor acting as a proxy to forward the Ajax call to corresponding services.

What is the recommended way?

**Comment by vigneshshanmugam** [comment]
@smilingleo Tailor could be used as a middleware here

```js
 http.createServer(request, response => {
    const url = request.url
    if (url.startsWith('api')) {
        // forward ajax calls to another service
    } else {
        tailor.requestHandler(request, response);
    }
})
```

**Comment by smilingleo** [comment]
@vigneshshanmugam thanks for your reply. 

If there are multiple fragments (from different fragment servers) in a template,  the middleware needs to know which fragment server to talk with, is there an easy way to know which fragment server the API request is from?

**Comment by vigneshshanmugam** [comment]
@smilingleo We use https://github.com/zalando/skipper as a router for handling the different API endpoints and routing them properly to the respective fragment server based on the route path. 

You could use https://expressjs.com/en/guide/routing.html router to do the same if you do not want to setup another routing layer.

**Comment by smilingleo** [comment]
@vigneshshanmugam thanks, skipper seems to be a good choice.
Another question, in Zalando, do you use skipper to route API requests or only UI requests?

**Comment by NorthFury** [comment]
@smilingleo skipper adds the following response header: `X-Powered-By:Skipper`. But to answer your question, API requests can also go through Skipper. In fact, it is quite convenient to have both your UI and API requests routed through Skipper.

**Comment by smilingleo** [comment]
Thanks a lot for your response, will close this one.
