### ISSUE TITLE
Communication between fragments

### ISSUE THREAD

**Issue by smilingleo** [zalando/tailor#142]
Let's say we have one template which has two fragments, the first to load a list page of order, the second to show statistics like how many active/draft/canceled orders. When the user clicks the `active orders` link, the first fragment shows only the active orders.

Is it a right approach to have these two fragments? (We want to manage the page layout by the template, say a page with 7-3 columns layout, to make sure all fragment servers are with consistent layout)

If so, what's the recommended way to share the state change between these two fragments, `localStorage` events?

**Comment by vigneshshanmugam** [comment]
We use event-bus for communicating with the fragments on the client side. A normal pub/sub mechanism which is available globally on the page for the communication works for us. It has both pros and cons. But IMO, you could go with whatever that works best for you. 

`localStorage` is also an option, but haven't evaluated them personally to give any comments on that. We even thought of having a shared mutable state in the Client but that comes with its own pros and cons. 

One such con of having the shared mutable state (session, local storage) is the need to keep the sync between server and client in case of network failures. Pub/Sub works here better since we don't care if the event is unavailable.

**Comment by smilingleo** [comment]
Thanks, make sense to me.

**Comment by SathishKumar140** [comment]
> We use event-bus for communicating with the fragments on the client side. A normal pub/sub mechanism which is available globally on the page for the communication which works for us. It has both pros and cons. But IMO, you could go with whatever that works best for you.
> 
> `localStorage` is also an option, but haven't evaluated them personally to give any comments on that. We even thought of having a shared mutable state in the Client but that comes with its own pros and cons.
> 
> One such con of having the shared mutable state (session, local storage) is the need to keep the sync between server and client in case of network failures. Pub/Sub works here better since we don't care if the event is unavailable.

In terms of local / session storage, an unknown person can crack easily our application.

Pub/Sub - Can you please share some example of how the communication is happening between the fragments? where the publisher will sit and how it can subscribe.

**Comment by vigneshshanmugam** [comment]
Assume the `events` library is present on the page and take `product` page for example and lets consider how adding a product to cart would make the cart UI to update the number of items in the cart

**cart.js**
```js
// This lies inside `cart.js` which is maintained by other team
events.on('add-product',  (count) => {
   updateCartUI(count)
})
```

**product.js**
```js
addEventListener('cart-button', () => {
   events.dispatch('add-product', 1)
})
```
Hope you get the idea.

**Comment by SathishKumar140** [comment]
> Assume the `events` library is present on the page and take `product` page for example and lets consider how adding a product to cart would make the cart UI to update the number of items in the cart
> 
> **cart.js**
> 
> ```js
> // This lies inside `cart.js` which is maintained by other team
> events.on('add-product',  (count) => {
>    updateCartUI(count)
> })
> ```
> 
> **product.js**
> 
> ```js
> addEventListener('cart-button', () => {
>    events.dispatch('add-product', 1)
> })
> ```
> 
> Hope you get the idea.

Is the event library is available in window level?

If it's available in the window, it can be easily cracked with dispatching an event from the console ( like chrome debugging console/snippets).

How to make it secure communication between two fragments?

**Comment by stevoPerisic** [comment]
One can argue that any kind of front end/UI communication is inherently not secure. If you have a need for transferring such sensitive data in the UI I would re-examine your architecture.

You should move the sensitive data comms to the back-end.

**Comment by SathishKumar140** [comment]
> One can argue that any kind of front end/UI communication is inherently not secure. If you have a need for transferring such sensitive data in the UI I would re-examine your architecture. You should move the sensitive data comms to the back-end.
> […](#)
> Sent from my iPhone
> On Jun 20, 2019, at 7:10 AM, Sathish ***@***.***> wrote: Assume the events library is present on the page and take product page for example and lets consider how adding a product to cart would make the cart UI to update the number of items in the cart cart.js // This lies inside `cart.js` which is maintained by other team events.on('add-product', (count) => { updateCartUI(count) }) product.js addEventListener('cart-button', () => { events.dispatch('add-product', 1) }) Hope you get the idea. Is the event library is available in window level? If it's available in the window, it can be easily cracked with dispatching an event from the console ( like chrome debugging console/snippets). How to make it secure communication between two fragments? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Agree on data comms part, A scenario like a script is triggering an event and it will be receiving in the micro-app (Here the event is not an actually triggered by our application) it's a loophole to hack the application, right?
