### ISSUE TITLE
What fragment should be the primary?

### ISSUE THREAD

**Issue by smilingleo** [zalando/tailor#146]
In my template, there are 3 fragments:
* navigation fragment which manages menu items and also the user session
* footer fragment
* the main function fragment
I prefer the navigation fragment as primary one since it manages the user session, for the unauthenticated request, it returns 401 so the page will be redirected to the login page.

But in general, the function fragment is the meat of the whole page, making it primary seems a nature thinking as well.

Any suggestion?
Thanks

**Comment by vigneshshanmugam** [comment]
Hmmm, IMO i will keep the functional fragment as primary and decide the status code based on the cookie/ single id that decides whether the user is anonymous or logged. By this way, the primary fragment can control the redirection logic or even return completely different components. 

By keeping it in the Header, you might end up in putting hacks for different pages. You might not need a user to be logged in for a home page in e-commerce context, but need them on cart/checkout pages. 

Hope this helps :)

**Comment by vigneshshanmugam** [comment]
Let me know if you need any help here otherwise we can close this one.
