### ISSUE TITLE
Weird issue - adding </body></html>

### ISSUE THREAD

**Issue by srcnix** [zalando/tailor#147]
While we are still trying to investigate this issue, I thought it worth mentioning it on here in case someone has already come across it.

We noticed recently that when our page content is larger than normal (We have only been testing with a few table rows, but recently moved to 10s of table rows) and the data is returned as chunked, tailor is doing two writes for the response instead of the previous, which was just one write. 

The first write is the entirety of the response without the following from the layout:

`</body></html>`

The second write is the remainder, which is the above missing HTML.

This is causing us an issue because we end the response on tailor "end" event, which we assumed would be when tailor has finished doing what it does best. 

      tailor.on('end', function (request) {
        response.end = _end
        resolve()
      })

So my question(s):
- Will tailor keep writing the response after "end" event is called?
- Does tailor add body and html closing tags if they are missing? I'm asking this because if I remove the two tags at the end of the layout they are still being written to the response.

**Comment by vigneshshanmugam** [comment]
I don't really follow, But I will try to explain your questions

> Will tailor keep writing the response after "end" event is called?

Yes, end event is fired when tailor started flushing the response to the browser. Dont rely on this event if you want to write any custom logic, Please use handleTag functionality specified in [options](https://github.com/zalando/tailor/#options) and the test case https://github.com/zalando/tailor/blob/master/tests/handle-tag.js.

> Does tailor add body and html closing tags if they are missing? I'm asking this because if I remove the two tags at the end of the layout they are still being written to the response.

Yes, tailor uses https://github.com/inikulin/parse5 as parser and it streams all the async fragments through async stream and appends the body and html closing tags. 

Let me know what you are trying to achieve and your example template, I will try to help as much i can.

**Comment by vigneshshanmugam** [comment]
@srcnix Do you need any other answers here?

**Comment by srcnix** [comment]
Apologies @vigneshshanmugam, I thought I responded to this.

The issue was in fact that we assumed the end event guaranteed that everything had been flushed. All fixed! Thanks again.

**Comment by vigneshshanmugam** [comment]
@srcnix Cool, Thanks!
