### ISSUE TITLE
Use the node v8 promisify API to remove unnecessary code

### ISSUE THREAD

**Issue by addityasingh** [zalando/tailor#153]
We can remove some unnecessary explicit `promisify` code by using the v8 `utils.promisify` API (https://nodejs.org/en/blog/release/v8.0.0/#improved-support-for-promises). 

E.g.: This [function](https://github.com/zalando/tailor/blob/master/lib/fetch-template.js#L29) can be changed to a much elegant and declarative implementation.

```javascript
const readFile = (path) => 
    new Promise((resolve, reject) => {
        fs.readFile(path, 'utf-8', (err, data) => {
            if (err) {
                reject(new TemplateError(err));
                return;
            } 
            resolve(data);
        });
    });
```
to

```javascript
const util = require('util');

const readFile = (path) => 
    util.promisify(fs.readFile)(path)
        .catch(err => new TemplateError(err));
```

**Comment by vigneshshanmugam** [comment]
Yup nice idea, but we need to polyfill it in lower versions. https://github.com/ljharb/util.promisify

**Comment by addityasingh** [comment]
Agreed. I will use this to have a polyfill for node 6.0 - node < v8.0

**Comment by dazld** [comment]
should promisfy once and use the returned function instead of doing it on every invocation.

**Comment by dazld** [comment]
ie:

```
const readFileP = util.promisify(fs.readFile); // or whatever

const readFile = (path) => readFileP(path)
                                               .catch(err => new TemplateError(err));
```
