### ISSUE TITLE
README clarity sought

### ISSUE THREAD

**Issue by LappleApple** [zalando/tailor#16]
A fan of the project says it's not very clear from the README what problems it solves--ie the awesomeness of Tailor isn't fully conveyed. I can edit/add if someone sends bullet points to address his issue. Info that expresses "what this solves and what you can do with it," "this is easy to use because ...," and "this is different from what's already out there because ..." will be great.

**Comment by w0rm** [comment]
@LappleApple we are working on the blog post about Tailor, maybe we can reuse the material to improve the readme. Will send you the draft once its ready.

**Comment by LappleApple** [comment]
Hey @w0rm and @vigneshshanmugam, I have time to help with the README this week. I have a template that makes README-writing super-simple and would like to follow that format. Can we do a 15/30-minute chat? Or you can just type out the answers. The template's in your Google Drive.

**Comment by vigneshshanmugam** [comment]
@LappleApple #31 Pleas take a look.
