### ISSUE TITLE
Loading a specific template insted of a folder

### ISSUE THREAD

**Issue by luizdesign** [zalando/tailor#170]
I'm trying use a specific template to more than one route like a layout with fragments to header and footer, so I need set a specfic template without relation to request's path.

**Comment by vigneshshanmugam** [comment]
Thanks for creating the issue.

Good catch, Not sure how we missed this part. Will take a look at the PR :)

**Comment by vigneshshanmugam** [comment]
Landed #171

**Comment by luizdesign** [comment]
@vigneshshanmugam Do you have any idea about a new version launch on the npm?

**Comment by vigneshshanmugam** [comment]
Thought of doing it once we land fix for #172 . But if its really urgent I can publish a new version

**Comment by luizdesign** [comment]
Relax man, It's just to bookmark on the our roadmap when we can use this version in production.

**Comment by vigneshshanmugam** [comment]
Cool 👍 

Are you guys using tailor in Production? If so would you be able to link me to the company, website or repo :)

**Comment by luizdesign** [comment]
In fact, we are testing tailor in a concept proof about a new front-end architecture, and making a release plan to launch a mvp. However, we don't define what technology will be used yet.

**Comment by vigneshshanmugam** [comment]
@luizdesign Cool, happy to answer any questions incase you guys need any help. 

Published a new version 3.1.1 with your changes. https://github.com/zalando/tailor/blob/master/CHANGELOG.md#311

**Comment by luizdesign** [comment]
Any others doubts or requests we will open new issues to discuss! =)

Thanks @vigneshshanmugam.
