### ISSUE TITLE
elements not arrangeable in columns

### ISSUE THREAD

**Issue by NikkyAI** [zalando/tailor#190]
using wordpress 4.8.2 and tailor 1.8.1 installed through wordpress
it seems impossible atm to put elements in collumn / next to each other

sadly i cannot be sure it might be CSS messed up by some other plugin or wordpress updates itself
will test later with a wordpress with _only_ Tailor installed

**Comment by DeTeam** [comment]
Hello @NikkyAI 

Is [this the plugin](https://de.wordpress.org/plugins/tailor/) you're working with?

This github repository is about something else. What you're probably looking for is this https://github.com/Enclavely/tailor github repo — maybe you could fill in issue there?

**Comment by NikkyAI** [comment]
wow.. how embarassing
