### ISSUE TITLE
Pass all/custom attributes to filterRequestHeaders

### ISSUE THREAD

**Issue by rbarilani** [zalando/tailor#207]
Hi, 

I have noticed that custom  attributes are not passed to `filterRequestHeaders`.
Is possible to pass all of them or there is a specific design decision behind this "restricted" behaviour?

Thanks.

**Comment by kevinsimper** [comment]
Hi @rbarilani 

You can either give your own filter function or use one of the headers that do not get filtered away. https://github.com/zalando/tailor#passing-information-to-fragments

The idea is that it is better to whitelist than it is to blacklist headers to avoid spilling user information.

**Comment by rbarilani** [comment]
@kevinsimper So to be sure that we are on the same track, here an example of what can be achieved if attributes are passed to `filterRequestHeaders`

Assuming my tailor server is running on http://localhost:3000 and the user as an active logged in session (req.user is populated, like if you are using passport.js)

template.html
```html
<fragment src="http://foo.com" authorization></fragment>
```

**filterHeaders.js (naif custom implementation)**
```js
module.exports = function customFilterHeaders(attributes, req) {
   if(attributes.authorization && req.user) {
     return { authorization: `Bearer ${req.user.accessToken}`}
   }
} 
```

The original function [filter-headers](https://github.com/zalando/tailor/blob/master/lib/filter-headers.js)
does something similar with `public` attribute but I would like to have more granularity.

**Comment by kevinsimper** [comment]
@rbarilani that looks fine to me, wouldn't that work for you? :)

**Comment by rbarilani** [comment]
@kevinsimper nope because `attributes` object  doesn't contain `authorization`, only "tailor well-known" attributes are passed: `id`, `src`, `public`, `async`, etc...

**Comment by rbarilani** [comment]
@kevinsimper didn't test it but I suppose that the code that "excludes" custom attributes is this one:

https://github.com/zalando/tailor/blob/master/lib/fragment.js#L16

**Comment by rbarilani** [comment]
Looking at the code I should be able to use `fetchContext` and `filterRequestHeaders` to get closer to what I want to achieve in the example, but I think having all the attributes is the expected behaviour.

**Comment by rbarilani** [comment]
@vigneshshanmugam @grassator @mo-gr @w0rm WDYT?

**Comment by vigneshshanmugam** [comment]
@rbarilani Sorry for the delay.

It was a conscious decision to not allow custom attributes from passing it down to fragments. The main reason being 

+ The way the template is structured and written out should be known only to tailor. 

+ Fragment developers can start abusing it in bad ways 

```html
<fragment src="blah" feature="enable-a, enable-b" />
```
The above is just a small example. This leads to cache invalidation at a much faster rate for templates. 

Since tailor is a middleware and only does the job of composition, You could handle the authorization logic in another middleware before sending the request to tailor. By this way the headers are filtered out and sent to all fragments. 

Hope this answers your question.

**Comment by rbarilani** [comment]
@vigneshshanmugam thanks for the answer.

> Fragment developers can start abusing it in bad ways

This is what I expected to heard. 😄 

> You could handle the authorization logic in another middleware before sending the request to tailor...

I don't want to control authorization (this is done in the way that you said) but control the way authorization is "passed" to fragments... or more in general which headers are passed to fragments by reading the value of the attributes in the `filterRequestHeaders` function... similar to what the original function does with `public` attribute but allowing more granular control...

**Comment by vigneshshanmugam** [comment]
Totally understood your concern and Its a valid request, But again this brings business logic/handling state which in first place tailor does not even know of since its handled inside another middleware. Personally, I do not want to encourage that behaviour. 

Thoughts? @mo-gr @grassator

**Comment by rbarilani** [comment]
>  But again this brings business logic/handling state which in first place tailor does not even know of since its handled inside another middleware....

@vigneshshanmugam Well this can be true for any customization entry point that this cool module provides... eg:

```js

const tailor = new Tailor({
  fetchContext: () => {
    return Promise.resolve({
        blah: {
          src: process.env.FOO_SRC // state
        }
    })
  },
 filterRequestHeaders: (attributes, req) => {
    // eg. of state added by passport middleware  
    if(req.user) {
       return {'X-User-Id': req.user.id }
    }
  }
});
```

As always just my 2 cents.  😄

**Comment by mo-gr** [comment]
I completely agree with @vigneshshanmugam that those concerns are better handled at another layer than tailor. But on the other side, I also don't see a lot of harm in passing all of the attributes on the fragment tag along. This probably makes tailor a bit more versatile.

@rbarilani would you be willing to make a PR for that?

**Comment by rbarilani** [comment]
@mo-gr Yeah I agree that those kind of things must be **better** done on some other layer (eg. on skipper) but I also like to start small and move to more complex architecture when is required, plus for little things, it can be useful.

> @rbarilani would you be willing to make a PR for that?

Sure. Will do.
