### ISSUE TITLE
Only resolve a fragment when the statuscode is 200 instead of below 500

### ISSUE THREAD

**Issue by leroy0211** [zalando/tailor#208]
Right now only when the `request.statusCode` is higher than 500 the `requestFragment` `Promise` resolves.

Whenever a fragment responds with a 404 (like default nginx) it displays the 404 response text on that fragment.

How I solved this (es6):

```
const tailor = new Tailor({
    requestFragment: (...props) => {
        return requestFragment(filterRequestHeaders)(...props)
            .then(response => {
                if(response.statusCode !== 200){
                    throw new Error("Non valid response");
                }
                return response;
            });
    }
});
```

**Comment by vigneshshanmugam** [comment]
The reason being 404 is a valid status code from the server and not an error like > 500 case and we do want that to be the default behaviour in tailor. But you are free to pass in custom requestFragment function through tailor [options] (https://github.com/zalando/tailor#options) and handle however you want.
