### ISSUE TITLE
Can NOT find template if there is a trailing slash in the request path

### ISSUE THREAD

**Issue by zhen-w** [zalando/tailor#210]
$ curl localhost:8100/orders/
template not found

**Comment by kevinsimper** [comment]
I think that is intentional

You should do some kind of URL rewrite like this or with `skipper`

https://github.com/zalando/tailor#passing-information-to-fragments

**Comment by vigneshshanmugam** [comment]
Yes it is intentional to handle the trailing slash through some middleware or proxy like Skipper.
