### ISSUE TITLE
Intercept response on primary fragment fetching error

### ISSUE THREAD

**Issue by dami-gg** [zalando/tailor#213]
We would like to know if you see any possibility to react to an error when fetching the primary fragment before setting the response's status code so that the server running Tailor can redirect to an error page.

Right now, on fragment fetching error, the stream is automatically ended and the status code is set to either 500 or 404.

We were first trying to do something based on fragment events, but the response is not available since it's already too late, due to the behavior explained before.

For you to understand better what we plan to do with this, we would like to implement a solution so that when a primary fragment fails to be fetched, most likely a navigation fragment owned by us, we redirect the user to a nice error page. 

In case of failure on any non-primary fragment, we plan to simply show an error fragment taking advantage of the default fragment attribute values (#211).

Any ideas or suggestions are more than welcome. Thanks!

**Comment by vigneshshanmugam** [comment]
For primary fragments, Tailor simply proxies the status code so primary fragment indeed controls the status code of the page. 

For the case of redirect, Please use 302 from your primary fragment and it should work without any issues.

**Comment by rbarilani** [comment]
@vigneshshanmugam How do you control the content of the failing response? Let's say that the fragment fails miserably 500 and it doesn't provide a fallback-src or even the fallback-src fails. What we will like to do in our application is intercepting this error and end the response by our self. e.g. redirecting to an error page or "render" directly an error view.

Another example is a fragment request that returns 401, the application hosting Tailor should be able to react accordingly. Eg.  redirect to `/login`, I know that this can be actually done by the "fragment" by sending back a 302 and the Location header, but this means that the fragment should know the right path to redirect to (coupling fragments with Tailor instance, introducing shared routing logic).

Eg. A solution without touching Tailor can be having a proxy (eg. Skipper) in between Tailor and the fragments that "adjusts" the responses, eg:

Tailor -> proxy -> fragment 401 -> proxy 302 /login -> tailor 

IMHO a little bit overkill for some Users.

WDYT?

**Comment by vigneshshanmugam** [comment]
What you can do here is, Since the [requestFragment](https://github.com/zalando/tailor/blob/master/lib/request-fragment.js) is called for each fragment request, You can provide a custom function to tailor and change the logic like this
```js
 default -  fragmentRequest.on('error', reject); // Instead of rejecting

fragmentRequest.on('error',  (err) => {
   if (fragmentAttrbites.fallbackSrc) {
        // Tailor handles the fallback Src, But if you want to act even on fallbacks, Then this is the 
        place
       resolve(customFallbackResponse)
   }
    resolve(response.pipe(fragmentStream) // Resolve with a new fragment stream
}
```

Hope this helps.

**Comment by vigneshshanmugam** [comment]
Since tailor is also a middleware, You could set up another middleware after tailor before flushing the response to the Browser if you want to extend the functionality.

**Comment by rbarilani** [comment]
@vigneshshanmugam Thanks we will try out using the suggested approach.

**Comment by vigneshshanmugam** [comment]
@rbarilani Did you try it out, Could you pleas close the issue if the method works?

**Comment by rbarilani** [comment]
@vigneshshanmugam Nope sorry, the project that was requiring this feature is not anymore live... so feel free to close this issue

**Comment by vigneshshanmugam** [comment]
@rbarilani Thanks

**Comment by dalisalvador** [comment]
> What you can do here is, Since the [requestFragment](https://github.com/zalando/tailor/blob/master/lib/request-fragment.js) is called for each fragment request, You can provide a custom function to tailor and change the logic like this
> 
> ```js
>  default -  fragmentRequest.on('error', reject); // Instead of rejecting
> 
> fragmentRequest.on('error',  (err) => {
>    if (fragmentAttrbites.fallbackSrc) {
>         // Tailor handles the fallback Src, But if you want to act even on fallbacks, Then this is the 
>         place
>        resolve(customFallbackResponse)
>    }
>     resolve(response.pipe(fragmentStream) // Resolve with a new fragment stream
> }
> ```
> 
> Hope this helps.

I've tried to do something like this but .on('response') event. If the error is 500 I then do something like:
```
fragmentRequest.on('response', response => {
            if (response.statusCode >= 500) {
                 const readableStream = fs.createReableStream(errorPage)
                readableStream.pipe(serverResponse)
                readableStream.on('end', () => reject(new Error())
            } else {
                resolve(response);
            }
        });
```

This "works"...  but as @dami-gg mentioned the stream is already ended, and headers already sent, giving a 
`Error: Can't set headers after they are sent`

I've created a middleware to prevent this but it's an ugly workaround... any ideas @vigneshshanmugam ??
thanks
