### ISSUE TITLE
Does this work on Angular 4

### ISSUE THREAD

**Issue by gustavofp** [zalando/tailor#220]
Hello, I'm trying to implement Tailor to load multiple Angular 4 apps. But i'm kinda confused due the lack of examples.

Does Tailor works on Angular 4? Is there any documentation or example of a Tailor app running multiple Angular fragments?

**Comment by kevinsimper** [comment]
Yes, it can support multiple angular apps, if you bundle them with webpack it should not matter if it is Angular or something else 😄 👍

**Comment by vigneshshanmugam** [comment]
Hey @gustavofp tailor is framework agnostic, It should just work with any framework out there. 


Tailor expects two things in general for any application to work.

1. The Final JavaScript bundle should be in AMD(Asynchronous module definition) or UMD(Universal Module Definition).
2. The Fragment endpoint delivering the content must send the JS/CSS bundles in the response Link Headers.
```js
response.writeHead(200, {
    'Link': `<${fragmentUrl}/bundle.css>; rel="stylesheet",` +
            `<${fragmentUrl}/bundle.js>; rel="fragment-script"`,
});
```

Checkout this [example repo](https://github.com/vigneshshanmugam/tailor-spa) that uses [Riotjs](http://riotjs.com/)

**Comment by bartekcajdler** [comment]
I checked it and Tailor works properly with vue and Angular 5. If you want to use Angular 5 as fragment, the best idea is prepeare simply webpack configuration (e.g. http://www.edc4it.com/blog/web/helloworld-angular2.html). Remeber to add umd library target ( libraryTarget: "umd"). If you want to use many angular framgents on one page you should exclude all polyfills (zone etc.) from code and put in in one vendor file and add it to Tailor templates.

**Comment by kolbis** [comment]
@bartekcajdler we are trying to run a sample of tailor + angular 7
we have yet to be successful.
can you maybe share your code example?

**Comment by melpakkam** [comment]
I am also looking for a a sample of tailor with Angular 7
