### ISSUE TITLE
Primary fragment not setting response code for page.

### ISSUE THREAD

**Issue by alex-roger-1942** [zalando/tailor#222]
Good day,

I'm really enjoying working with Tailor, it's an amazing product - but I think I might be misunderstanding some of the documentation.

I have a primary fragment.

`<fragment src="http://mydomain.com/some-fragment" primary></fragment>`

Everything works as expected. The page loads slick along with my other fragments and the react components are all AMD modules.

However as expected on lower end devices the timeout occurs (default 3000) . The primary fragment then fails.

```
Uncaught Error: Load timeout for modules: http://mydomain.com/some-fragment/bundle.js
http://requirejs.org/docs/errors.html#timeout
    at makeError (require.min.js:1)
    at checkLoaded (require.min.js:1)
    at require.min.js:1
```

The chrome tools show (cancelled) for the bundle.

However my page still returns a 200. How do I then handle this in my tailored html page to inform the user?

My other fragments have loaded and I now have an incomplete page. Somepage.html with a 200 in?

Do I plug into Tailor hooks here and add javascript? The documentation was a bit unclear to me on this part.

Thank you for your time.

**Comment by stevoPerisic** [comment]
My suggestion is to always have a fallback for your fragment. Just include a ```fallback-src="[your-route]/fallback"``` in your fragment tag.

**Comment by alex-roger-1942** [comment]
I will consider adding this, however I would still like to be able to understand how to handle this, since on primary fragments displaying a whoops something went wrong on a default 500 page with a redirect makes most sense to me. (also in the case something like the fallback errors)

**Comment by alex-roger-1942** [comment]
@vigneshshanmugam would you perhaps be able to clarify?

**Comment by vigneshshanmugam** [comment]
> However as expected on lower end devices the timeout occurs (default 3000) . The primary fragment then fails.

Hey, the default timeout(3000) in tailor refers to backend timeout for your fragments and does not apply to assets(JS) timeouts. The default timeout for a request in browser is 60 seconds and since we are using requireJS for module loading, you can change the default timeout (7 seconds) http://requirejs.org/docs/api.html#config-waitSeconds
