### ISSUE TITLE
Socket Hang Up and Keep alive

### ISSUE THREAD

**Issue by ghost** [zalando/tailor#223]
Hi there,
Thanks for this great project !

We have done some stress tests and sometimes during load (randomly) we get those kind of errors : 

 Error: socket hang up\n    at createHangUpError (_http_client.js:331:15)\n    at Socket.socketCloseListener (_http_client.js:363:23)\n    at emitOne (events.js:121:20)\n    at Socket.emit (events.js:211:7)\n    at Socket.wrapped [as emit] at TCP._handle.close [as _onclose] (net.js:567:12) code: 'ECONNRESET' 

This error means that the connexion (tailor server to fragment endpoint) has been closed while the response isn't complete. One workaround was to increase the fragment timeout but it's not our wish. I precise that the remote server is AWS edge with a lot of cache so the response time is very fast everytime (below 20ms).

We tried to use the keep alive parameter to avoid recreating http connexions, but it doesn't seems to work, node is not able to reuse the connexions, we observe a saturation of server sockets.

Did you experience those kind of issues ? Did you find workarounds ?

Regards
Fred.

**Comment by vigneshshanmugam** [comment]
Hey, internally we use a extended version of tailor by implementing our own [requestFragment function](https://github.com/zalando/tailor/blob/master/lib/request-fragment.js#L22)

We use https://github.com/node-modules/agentkeepalive which helps with keep-alive agents and you can configure both TCP and HTTP keep alive timeouts there. 

The other solution we did before was using a custom Agentpool logic 

1. Use a queue to maintain the list of Agents (Maximum 3 agents in our case).
2. Create a new HTTP or HTTPS Agent and mark this new agent as the current Agent.
3. Serve all the traffic through the current Agent for specified intervals.
4. Follow step 2 and 3 and mark the old Agent as inactive.
5. Do this till we hit our maximum 3 agents and recycle the old agents.
