### ISSUE TITLE
Handling more than just bundle.js in the fragment

### ISSUE THREAD

**Issue by tsnolan23** [zalando/tailor#230]
With an application that includes a dependency such as `font-awesome`, when you build the application with webpack, it outputs more than just a `bundle.js` file. It also contains some hashed font files. 

The tailor template only looks for the `bundle.js` which means the other assets cannot be found when the page loads. 

Is there any way to handle these assets?

**Comment by vigneshshanmugam** [comment]
You can use the [maxAssetLinks option](https://github.com/zalando/tailor#options) which can increase the number of assets to be downloaded from fragment server.
