### ISSUE TITLE
Add tracing instrumentation

### ISSUE THREAD

**Issue by lmineiro** [zalando/tailor#231]
Tailor is often used as part of large-scale distributed systems and providing out of the box tracing support will extend the observability already present.

[Opentracing](https://opentracing.io) has gained enough traction and community support to be considered the current standard way of providing distributed tracing across polyglot systems.

The goal of this issue is to [instrument the basic operations first](https://github.com/opentracing/opentracing.io/blob/master/_docs/pages/instrumentation/instrumenting-large-systems.md#crawl-walk-run), preparing the environment to provide a global tracer which can later (with separate issues) be used to instrument all other missing operations.

**Comment by vigneshshanmugam** [comment]
closing in favor of #232 #236
