### ISSUE TITLE
is it possible to use multiples angular 6 apps like a portal ?

### ISSUE THREAD

**Issue by thiswallz** [zalando/tailor#242]
I need to do a Portal and this portal is going to call several angular 6/5 apps in a div container.
this portal has only a menu and when I click on 1 of those it would have to load an app.
These apps are hosted even in different servers and domains.

Is that possible to achieve with this stack (zalando) or you recommend something else?

I don't want to use iframes but it seems sadly like the best option so far.

thanks guys

**Comment by kevinsimper** [comment]
@thiswallz If you can archive putting multiple angular apps together manually, then tailor can help you do it on the fly :)

**Comment by vigneshshanmugam** [comment]
If you want to load those apps conditionally, then tailor wont be the best option.
But if you want to load(Stream) them in one go and do a switch in front end then tailor would totally work.
