### ISSUE TITLE
Tailor with Express js

### ISSUE THREAD

**Issue by deepmy** [zalando/tailor#246]
Is there any way to use Tailor with express?

**Comment by DeTeam** [comment]
@deepmy sure, in the simplest case `tailor.requestHandler` function takes standard nodejs.http objects which are available in express. Do you think of some more advance/concrete integration?

**Comment by vigneshshanmugam** [comment]
Indeed you can, you could simply do this

```js
app.get('/*', tailor.requestHandler) // for all html pages
```
