### ISSUE TITLE
[Question] Handling conflicting CSS between fragments

### ISSUE THREAD

**Issue by imduffy15** [zalando/tailor#250]
Hi,

This is potentially a silly question as my frontend knowledge is very limited.

I'm trying to understand how common dependency management is handled.

Is there anything to prevent leaking CSS between different fragments or is there a way to automatically scope each fragments CSS?

For example, if a fragment give a CSS file containing:

```
body {
    background-color: black !important;
}
```

Will it affect only that fragments body or everything?

**Comment by clitcancer** [comment]
Css in html is global. Therefore yes, your css will leak and be applied to other fragments too. Personally I currently solve this issue by adding a `_microfrontendName` suffix to my css classes to make sure they don't intersect. Maybe tailor could apply it to coming fragments?  Would be nice.

**Comment by imduffy15** [comment]
> Therefore yes, your css will leak and be applied to other fragments too.

Makes sense.

> Personally I currently solve this issue by adding a _microfrontendName suffix to my css classes to make sure they don't intersect. Maybe tailor could apply it to coming fragments? Would be nice.

Me too, I make use of VueJS's CSS Loader to do scoping, it works nicely: https://vue-loader.vuejs.org/guide/scoped-css.html#mixing-local-and-global-styles

**Comment by imduffy15** [comment]
Is it possible to get conflicts between JavaScript libraries too or are
they scoped in some way?

For example, let’s say two different fragments require different offers to
versions of jquery.

**Comment by clitcancer** [comment]
Depends how you include it. If with a `<script>` it becomes global which might cause conflits. Best practice would be to encapsulate everything you do in a microfrontend to maximise independence.
For example in a React project you would use webpack to transpile everything into one encapsulated js file.

**Comment by imduffy15** [comment]
Thanks for the help @clitcancer

**Comment by vivek-kandhvar** [comment]
> Depends how you include it. If with a `<script>` it becomes global which might cause conflits. Best practice would be to encapsulate everything you do in a microfrontend to maximise independence.
> For example in a React project you would use webpack to transpile everything into one encapsulated js file.
> A simple example to prevent global variables would be closing everything in an anonymous function
> 
> ```js
> (() => {
>   // Your code
> })()
> ```

We are also facing java script conflicts. Can you let me know more about this solution? How and where do I encapsulate the bundle.js?

**Comment by shilangyu** [comment]
@vivek-kandhvar can you give me more details? By default webpack's bundle is encaplusated

**Comment by kevinsimper** [comment]
@imduffy15 Webcomponents will help you with Shadowdom, as it helps with CSS to be encapsulated 👍
