### ISSUE TITLE
Redux implementation using Tailor

### ISSUE THREAD

**Issue by rizdaputra** [zalando/tailor#253]
I have some noob question. Can i implement Tailor using redux? How can i pass state between the fragments?

**Comment by kevinsimper** [comment]
Tailor wouldn't interact with Redux as Tailor makes a page with your two React applications. The way to test it before you be to make a page with two React application that talks together 😄 👍

**Comment by vigneshshanmugam** [comment]
As @kevinsimper pointed out, Tailor doesn't care about how you deal with state management. 

But you could use any state management libraries(redux, mobx) to communicate between fragments, We use plain publisher-subscriber patter to deal with cross state communication between fragments.
