### ISSUE TITLE
Sever side rendering SSR

### ISSUE THREAD

**Issue by morriq** [zalando/tailor#255]
First of all - thank you for your work, it's really awesome project.

Readme.md says `Composes pre-rendered markup on the backend. This is important for SEO and fastens the initial render.`

It works with simple cases, but I run https://github.com/tsnolan23/tailor-react-spa (which is great) and there it no render markup on backend (which is understable). I wonder how can we achieve ssr in such cases?

Probabbly I'll start for example here https://github.com/tsnolan23/tailor-react-spa/blob/master/packages/fragment-header/fragment.js#L15 and try to call `ReactDOMServer` but it seems to be peak of the mountain. Does anybody achieve that?

Regards

**Comment by kevinsimper** [comment]
There is some really great examples here https://github.com/zalando/tailor/tree/master/examples especially the https://github.com/zalando/tailor/tree/master/examples/basic-css-and-js is good to try 😄 👍

**Comment by morriq** [comment]
Thank you for your answer.
Sorry for not being precise, but I was looking in react project . I'll update my first comment.

**Comment by kevinsimper** [comment]
Tailor only combines output from multiple servers, so first figure out how to do server rendering with one server and react, and then you can use Tailor to fetch that from that server 😄 https://reactjs.org/docs/react-dom-server.html

**Comment by morriq** [comment]
Just fyi I created fork of tailor-react-spa with ssr in vue and react. If someone need it:

https://github.com/morriq/tailor-react-spa
