### ISSUE TITLE
Assets are loaded twice for the primary fragment

### ISSUE THREAD

**Issue by cbm-othomas** [zalando/tailor#272]
Hi,

node-tailor version: 3.9.2

I noticed in the network devtools that the **primary** fragment assets are loaded twice.
This does not break the application but it 's weird.

![assets](https://user-images.githubusercontent.com/43334674/48890713-d7733b80-ee39-11e8-83ae-48d963d6e1a6.png)

The header of the template request contain a link header with a reference to this file.

`
Cache-Control: no-cache, no-store, must-revalidate
Connection: keep-alive
content-type: text/html; charset=utf-8
Date: Thu, 22 Nov 2018 08:35:55 GMT
link: <https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.22/require.min.js>; rel="preload"; as="script"; nopush; crossorigin,<http://a58bbba9b1f.js>; rel="preload"; as="script"; nopush; crossorigin
Pragma: no-cache
Transfer-Encoding: chunked
X-Powered-By: Express
`

In the fragment server we add this header for the asset:
`res.setHeader('Link', `<http://a58bbba9b1f.js>; rel="fragment-script"`);`

Thanks

**Comment by kevinsimper** [comment]
Hi @cbm-othomas 

You can see that there is two different `Initiators`, one loaded by a script tag probably and the other by require.js

Can you see that script tag in the html that was loaded?

**Comment by vigneshshanmugam** [comment]
@cbm-othomas We sue preloading technique for assets from primary fragment to improve the Time to Interactive of the web page. 

you can learn more about these here - https://w3c.github.io/preload/#ex-2-using-http-header

The issue on asset being loaded twice is a chrome bug and its already fixed on new version of chrome, Please check the status here - https://bugs.chromium.org/p/chromium/issues/detail?id=794958
