### ISSUE TITLE
Fragment from HTTPS server

### ISSUE THREAD

**Issue by sixdouglas** [zalando/tailor#278]
I’ve successfully setup Taylor to output HTTPS. 
But my fragments are also from HTTPS servers and I didn’t manage to make Taylor works with those. 
What part of Taylor should I customize to handle those secured fragments ?

**Comment by DeTeam** [comment]
@sixdouglas https://github.com/zalando/tailor/blob/master/lib/request-fragment.js#L49 Tailor supports fragments' https endpoints out of the box. Are you experiencing some issues?

**Comment by sixdouglas** [comment]
Thanks for this quick reply. 
The problem is that I have a server error without any more information. The samples work fine though. Do you know if the redirections are followed natively? I had to add this mechanism in a Spring Boot project while dealing with SSL connection. 
Thanks

**Comment by DeTeam** [comment]
> Do you know if the redirections are followed natively?

No they are not, in case if you need this functionality you can provide a custom `fetchFragment` [option](https://github.com/zalando/tailor#options) to Tailor (be aware of infinite or too many redirects, though).

> Redirects

Normally you'd want to actually redirect you users if `primary` fragments returns 301/302, so you'd have to understand where is a redirect http->https (misconfiguration?) and where it's a legitimate part of expected user experience.

**Comment by trickpeeraze** [comment]
This is the same case I've faced about redirection and already open the discussion at #268. But how I solved this is to create a new `requestFragment` function to specially handle following redirect and force that to attempt only one time avoiding _"infinite or too many redirects"_. I hope this will help @sixdouglas 😬

**Comment by sixdouglas** [comment]
@trickpeeraze many thanks for sharing! I’ll take a look at it. 
Though, I’m wondering if my problem comes from my HTTP/2 SSL fragment supplier server. 
It looks like tte support is still experimental in NodeJs...

**Comment by sixdouglas** [comment]
Here is an update, I moved to the last Node Version 11.4 and now I have a real error message! It seems that my certificate has expired! So I've generated a new self-signed one and now I have an other error :
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'link' of undefined
Not liked with the subject of this error. I'm closing this issue.
Thanks for all your help guys.

**Comment by raguipri** [comment]
Hi there, sorry to write in a closed issue but I am having problems retrieving fragment from an https service. 
I  am listening fragment:start, fragment:response and error's tailor events, only fragment:start is triggered, and I don't see any error in my logs. The only way to retrieve the fragments is setting ENV NODE_TLS_REJECT_UNAUTHORIZED=0, which is not a valid solution. 
Any tips on how to solve this? Thanks

**Comment by vigneshshanmugam** [comment]
If you are using self signed certificate in your fragment, this is one of the reasons why you wont get the response event getting triggered. 

You could listen to 'error' event on fragment and log the error or you can pass the certificates when making https requests https://nodejs.org/dist/latest-v10.x/docs/api/https.html#https_https_request_url_options_callback

**Comment by stevoPerisic** [comment]
Hi Vignesh,
Does this mean we would have to update the tailor https options object to
pass the certs? How can we do this without a PR to the Tailor codebase?

**Comment by vigneshshanmugam** [comment]
Tailor can be customised here, you can supply your own requestFragment function and you could pass in the custom certificates as part of making the https requests. https://github.com/zalando/tailor#options

`**requestFragment(filterHeaders)(url, attributes, request)** - Function that returns a promise of request to a fragment server, check the default implementation in lib/request-fragment
`
