### ISSUE TITLE
Dockerize the microfrontends application

### ISSUE THREAD

**Issue by kanhery** [zalando/tailor#281]
Hi Team,

I want to put all fragments and backend into a docker container.
Challenge is how to replace fragment src/urls in index.html dynamically ? 

taking example of https://github.com/tsnolan23/tailor-react-spa 
How do I replace localhost of fragments with IP address of machine on which my docker is running ?

please throw some light on this.

**Comment by morriq** [comment]
Hello.

see this one. maybe it will help you:
https://github.com/morriq/Frontend-microservices/blob/master/docker-compose.yml#L26

**Comment by kevinsimper** [comment]
> How do I replace localhost of fragments with IP address of machine on which my docker is running ?

That is a very specific question that really requires to see your implementation to really help 😄 

But Tailor is really flexible and you can essentially rewrite every on the fly, so both templates, req and res can be changed while it is running to fit dynamically 😄

**Comment by stevoPerisic** [comment]
You have to find the IP of the network that Docker creates when you run
docker-compose, than in your YAML file where you are declaring the
definitions of your microservice-containers you can add the

extra_hosts:
  localdev: [network IP]

That will point all the requests correctly
