### ISSUE TITLE
how navigation works without full page reload

### ISSUE THREAD

**Issue by askbeka** [zalando/tailor#284]
Hi, I am trying to understand how things work in Mosaic.
Fragment is a html hosted somewhere, then I map it to skipper and reference it in fragment.

But when in my navbar route is changed, will the whole page need to reload since backend sends those fragments?
If not how do you import html in client side without reloading the page?

**Comment by vigneshshanmugam** [comment]
Yes every page request is a full reload and every time browser requests a new page, they get routed to different endpoint through skipper to tailor where the templates are stored. 

You could make SPA work with reload, but requires some front end route logic. Check here https://github.com/vigneshshanmugam/tailor-spa
