### ISSUE TITLE
middleware for processing fragment response

### ISSUE THREAD

**Issue by j0hnys** [zalando/tailor#285]
Hello.

Is there a way to process the response that comes after a fragment fetches data from it's url? Something like a middleware that can be used to manipulate the content of the response for each fragment individually. 

Thank you.

**Comment by vigneshshanmugam** [comment]
@j0hnys Tailor does have [events](https://github.com/zalando/tailor/blob/master/docs/Events.md#fragment-events) for fragment: response and fragment: end when it receives responses from fragments, But it does not expose the response stream itself. 

If you want to act on the response stream itself, then the only option is supplying your own version of [requestFragmen](https://github.com/zalando/tailor#options) function that fetches and modifies the content of fragment stream.

**Comment by j0hnys** [comment]
@vigneshshanmugam  Ok, I understand. I will look into it. If you give me some hints on where to look at and what to change in order to make something like this work then I might find some time to implement this feature for the upstream.

Regardless, thank you for your quick response.

**Comment by vigneshshanmugam** [comment]
@j0hnys Sure, check this source
https://github.com/zalando/tailor/blob/654b4b83b4809775d8bc5962206d0595c8a417b5/lib/request-fragment.js#L50-L62

```js
// before
resolve(responce)

//You would need to pipe it to a middleware function which would take a 
// response stream and send a modified stream instead
const applyMiddlewares = (response) => {
  // logic stays here
}

return resolve(applyMiddlewares(response))
````

**Comment by j0hnys** [comment]
@vigneshshanmugam Thank you very much Vignesh. This is very helpful! Cheers.
