### ISSUE TITLE
(Re-)Implement support for custom attributes?

### ISSUE THREAD

**Issue by thoras** [zalando/tailor#287]
With #247, fragment attributes have been trimmed down to a selection of default properties and thus support for custom attributes has been removed. We’re using v3.7.1 in our project (the last version supporting the old attributes handling) as we liked to implement custom properties and take those into consideration within a custom `requestFragment` handler.

Is there any plan to (re-)implement support for custom attributes? For example by specifying the allowed custom properties within the setup options.

**Comment by vigneshshanmugam** [comment]
@thoras good catch. Will try to fix it ASAP.
