### ISSUE TITLE
Communication between fragments

### ISSUE THREAD

**Issue by gAllegr** [zalando/tailor#294]
I'm trying to use Tailor to build a microfrontend with 5-6 Angular 7 application.
I managed to compose the single page with all apps and I'm now trying to make them communicate.

**What I'm trying to do**
One application has a button that, when clicked, would send some information to another application.

**What I've already tryed**
HTML5 WebStorage API, but it doesn't work because applications are on the same window/tab.
Custom Event, but it seems that the event created in one Angular application is not passed to the container page (the one that compose all Angular apps).

I read this [issue](https://github.com/zalando/tailor/issues/292)
_Regarding passing data to fragments the only way is through the headers as you have already implemented._

There is no way to pass data between fragments composed on the same page?
If there is no way, will Skipper help with that communication handling?

**Comment by stevoPerisic** [comment]
Create custom events on the browser window object, this is the natural way to pass events within the browser.
https://developer.mozilla.org/en-US/docs/Web/API/Window/event
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent

**Comment by shilangyu** [comment]
[Example with native Custom events](https://github.com/tsnolan23/tailor-react-spa/issues/7#issuecomment-424267024) (redux aspect can be ignored)

**Comment by kevinsimper** [comment]
Like microservices on the backend, microservices on the frontend can expose an API that other app can use. However, it comes with complexity and it often gives an unwanted effect where the apps become tightly coupled.

A better approach would be to let each app talk to an HTTP backend and have the other listen on that backend. That will keep the logic on the backend and contained, and will not tightly coupled the frontend.

**Comment by vigneshshanmugam** [comment]
I have answered to similar question here - https://github.com/zalando/tailor/issues/142#issuecomment-294771383.

**Comment by gAllegr** [comment]
Thanks all for your answers.
I tried again using Custom Events, I was coding them in an improper way. Fragments now communicate correctly.
