### ISSUE TITLE
Handle tags could not be used into head tag

### ISSUE THREAD

**Issue by cbm-othomas** [zalando/tailor#299]
Hi,
tailor version: `node-tailor: 3.9.2`
os: linux
browser: chrome

I try to add a custom tag into the `<head>` tag.
The template look like that
```
<!DOCTYPE html>
<html>
<head>
    <jsscript></jsscript>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

    <h1>Example of custom tag into head</h1>
</body>
</html>
```

So I imagine that the custom tag to be inside the `<head>` tag. But when I call the page I get this:

```
<!DOCTYPE html>
<html>
   <head>
   </head>
   <body><script src="https://polyfill.io/v3/polyfill.js">
      </script>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title>Page Title</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <h1>Example of custom tag into head</h1>
   </body>
</html>
```
I use the tailor example `custom-tag` to adapt this. https://github.com/othke/tailor/commit/c1e20c3fa5c1d83a5a51f3659e3b10ad03b562e8

Do I miss something ? Or is there something special with the parser and the `<head>` tag ?

Thanks

**Comment by cbm-othomas** [comment]
I check parse5 and I noticed the result of head is not good when you add a fragment tag inside
https://astexplorer.net/#/gist/7f3460102c9c3e6615a724e1faf7b437/8d3d325bd25825dbbeeabab5815cad2222c6477f
This is the version 5 of parse5 but we have the same result in tailor with the version `3.0.3` and the `htmlparse2` treeAdapter.

**Comment by vigneshshanmugam** [comment]
Custom elements are always pushed to the body while parsing HMTL, If you want to use custom elements in the head, you can do it via script tags

```html
<script type="jsscript"></script>
```

Check this test https://github.com/zalando/tailor/blob/654b4b83b4809775d8bc5962206d0595c8a417b5/tests/tailor.js#L201-L226

Hope this helps.
