### ISSUE TITLE
Frontend tests fail for external contributors due to Saucelabs

### ISSUE THREAD

**Issue by addityasingh** [zalando/tailor#300]
Frontend tests fail for external contributors due to Saucelabs. Examples:
- https://travis-ci.org/zalando/tailor/jobs/468800950
- https://travis-ci.org/zalando/tailor/jobs/514400191
- https://travis-ci.org/zalando/tailor/jobs/513914175

In order to resolve this, we need to either check if we really need saucelabs or using something like puppetteer would be just fine

**Comment by vigneshshanmugam** [comment]
Its bcoz all of the contributors are forking the project and then contributing code, encrypted tokens wont work for forks 
```
Pull requests sent from forked repositories do not have access to encrypted variables or data even if these are defined in the fork source project.
```
You can read more about this here - https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions

**Comment by vigneshshanmugam** [comment]
No way around if we need to run on saucelabs without exposing the tokens. 
1. You can simply expose the tokens without encrypting it and it would work for everyone. 
2. Remove saucelabs and add `selenium` or something to run it on the browsers.

**Comment by addityasingh** [comment]
Would it make sense to only run the frontend tests selectively i.e. for changes to the Tailor client side code?

**Comment by vigneshshanmugam** [comment]
No that will fail to catch errors when we pipe things from backend. It should run for all changes. We insert script tags from backend and if there is an issue we should be able to see it affecting the frontend tests.

**Comment by addityasingh** [comment]
That sounds reasonable. Let me do that change

**Comment by addityasingh** [comment]
In the current structure, using the `examples/fragments-performance/hooks.js` for running a test doesn't seem right. For now I will make this change but maybe the `fragment-performance` example should be moved to test?
