### ISSUE TITLE
What is the difference  between Tags and Fragments?

### ISSUE THREAD

**Issue by kolbis** [zalando/tailor#305]
1. What is the motivation for using handledTags and handleTag handler? 
2. What does it differ from creating a fragment?

**Comment by kolbis** [comment]
@vigneshshanmugam 
Maybe you can help with the above.

**Comment by vigneshshanmugam** [comment]
@kolbis Thanks for bringing it up. Its an interesting question and simple answer is just we need to treat fragments in different way than other tags on the template. 

> What is the motivation for using handledTags and handleTag handler?

When we are in need to inject some common HTML on all of the pages, we utilise the handleTags and handleTag handler. An example would be to inject some code for gathering performance on all pages. 

```html
<script type="perf-hooks"></script>
```

```js
const tailor = new Tailor({
    handleTags: ['perf-hooks'],
    handleTag: (request, tag) => {
      switch (tag.name) {
        case 'perf-hooks':
          return `
            <script>
              ((function measurePerformance){
                 // code
              })
            </script>
          `
        default:
          return ''
      }
    }
  })
```

**Note**: You can also fetch from a remote endpoint and do whatever you want to do on the page like injecting analytics, A/B tests and whatnot. 

> What does it differ from creating a fragment?

Fragment tags are pretty strict in nature, Their functionality is just to return HTML and Link headers for CSS & JS to be used on the page. They can't return JSON or any other formats. But with handleTags we can do all of those and its just a way of extending the functionality of tailor for composing arbitrary formats. You could go crazy and completely run the page rendering JSON documents from backend just with different tags and not use any of the fragment functionality. Another possibility with handleTag is supporting `nested fragments`.  Check out this test for example https://github.com/zalando/tailor/blob/08805cbbdb9b1a393c4b786e7b05ed06093a6eaa/tests/process-template.js#L50-L70

Hope it helps.

**Comment by kolbis** [comment]
@vigneshshanmugam I appreciate the answer.
So based on your answer, I assume that for all the meta tags, you would recommend using as tags, correct? Any other recommendations here?

<Title ../>
<meta canonical=... />
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="dns-prefetch" href="https://XXX.com">
<meta name="description" content="XXX">
<meta name="robots" content="INDEX,FOLLOW">
<link rel="alternate" hreflang="en-GB" href="XXX">
<meta property="al:ios:app_store_id" content="XXX">
<meta property="al:ios:app_name" content="XXX">
<meta property="al:ios:url" content="XXX">
<meta property="fb:app_id" content="XXX">
<meta property="p:domain_verify" content="XXX">
<link rel="icon" type="image/x-icon" href="https://XXX.ico">

**Comment by vigneshshanmugam** [comment]
@kolbis Yeah meta tags are a great example and also for any common snippet that is going to be present on all the HTML pages.
