### ISSUE TITLE
Send Authentication Header for Fragments

### ISSUE THREAD

**Issue by rafasf** [zalando/tailor#325]
Hi there, looking at the options I didn't quite find the right place to include a header to be sent to the fragment when fetching it.

Is it possible?

Thanks.

**Comment by kevinsimper** [comment]
That is on purpose, but you can pass information like the request uri :)

https://github.com/zalando/tailor#passing-information-to-fragments

**Comment by rafasf** [comment]
From what I noticed, if I add the header to the `request` it gets removed in `filter-headers` since it isn't part of `ACCEPT_HEADERS`.

Is there a way to white list other headers?

Thanks.

**Comment by kevinsimper** [comment]
You can provide a `filterRequestHeaders` function as option 
https://github.com/zalando/tailor#options

The default is this one https://github.com/zalando/tailor/blob/master/lib/filter-headers.js

**Comment by stevoPerisic** [comment]
You can edit/load your own array of the ACCEPT_HEADERS to get what you need across.

Let me know if you need a code sample.

**Comment by rafasf** [comment]
Cool! Thanks. I was able to do what I was trying. 🎉
