### ISSUE TITLE
Questions about Tailor

### ISSUE THREAD

**Issue by danielbayerlein** [zalando/tailor#34]
I'm not sure whether an plain HTTP server (http-module) is the right thing. Do you use the plain HTTP server (http-module) in production?

Works Tailor with @hapijs? @hapijs has many useful modules.

* Where is the security layer - Fragment or Tailor?
* Do you have an example for a more complex URL routing with dynamic and static parameters?

A more complex example would be great.

**Comment by vigneshshanmugam** [comment]
Nope, we use a custom fork of tailor which fetches the templates using https (zalando specific agents). 

Right now, I don't think it works with `hapijs`. I think we can hack the code a bit and make it work. Not 100% sure though.

Both Tailor and deployed Fragments are separate stand alone micro services, If you are looking for making your end point secure, you can simply hack the way we [request fragment](https://github.com/zalando/tailor/blob/master/lib/request-fragment.js) and implement some OAuth solution on top. 

Not sure I understand your last question. In production, we use [Skipper](https://github.com/zalando/skipper) for managing and controlling the routes. The requests from the browser first hits Skipper, then they are routed to Tailor which composes the page.

**Comment by danielbayerlein** [comment]
Thank you very much for the informations, @vigneshshanmugam!

I have a few questions :blush: - sorry!

* If you do not use `require('http')`, which server you use then?
* Do you use modules like https://github.com/krakenjs/lusca or https://github.com/helmetjs/helmet for web security?
* Is my flow chart correctly?

![tailor](https://cloud.githubusercontent.com/assets/457834/15921559/894fd9f6-2e22-11e6-8b03-9518c92e8bc0.JPG)

**Comment by vigneshshanmugam** [comment]
Hats off to the flow diagram 👍 

+ We use plain nodejs [https](https://nodejs.org/api/https.html) module with zalando specific agent (means zalando specific certificates)
+ Not right now, But Skipper does handle some security issues like XSRF. We are planning to add some meta tags for security like CSP. 
+ Yes the flow is exactly the same. Tailor just assembles/composes the fragments. 

Hope I answered your questions.

**Comment by danielbayerlein** [comment]
@vigneshshanmugam Thanks a lot! Do you use a service discovery for multiple service instances?

**Comment by danielbayerlein** [comment]
@vigneshshanmugam || @aryszka 

I'm testing Skipper and Tailor and have a problem. 😢 

Tailor runs on `http://localhost:3000` and has a `catalog.html` and a `category.html` template.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>frontend-microservices</title>
  </head>
  <body>
    <h1>frontend-microservices: category.html</h1>
    <fragment src="http://localhost:3001" primary>
    <fragment src="http://localhost:3002" async>
  </body>
</html>
```

My Skipper routes file:

```
catalog: Path("/catalog") -> "http://localhost:3000";
category: Path("/category/:id") -> "http://localhost:3000";
```

My first request is `http://localhost:9090/catalog` - works!
Next request: `http://localhost:9090/category/123` - doesn't work!

Skipper forward the request to `http://localhost:3000/category/123`. Tailor responds with http status code 500, because the template `category/123` doesn't exists.

How to handle this? Sorry, I'm not familiar with Tailor and Skipper.

**Comment by mo-gr** [comment]
Your route needs to look something like this:

`category: Path("/category/:id") ->  modPath(".*", "/category") -> "http://localhost:3000";`

**Comment by danielbayerlein** [comment]
@mo-gr Thanks a lot!

**Comment by vigneshshanmugam** [comment]
@danielbayerlein Refer here for full docs - http://www.mosaic9.org

**Comment by danielbayerlein** [comment]
@vigneshshanmugam Awesome!

**Comment by rikkert** [comment]
@danielbayerlein How do you receive the id now in your fragment service?
I'm having trouble to get that running.
Skipper replaces it from the path so tailor can map it to the right fragment service but how does it receive the request id :?
