### ISSUE TITLE
Tailor example is not working

### ISSUE THREAD

**Issue by Mohammed-Aadil** [zalando/tailor#39]
Tailor started at port 8080
Fragment1 started at port 8081
Fragment2 started at port 8082
_http_outgoing.js:309
      throw new TypeError('The header content contains invalid characters');
      ^

TypeError: The header content contains invalid characters
    at storeHeader (_http_outgoing.js:309:13)
    at ServerResponse.OutgoingMessage._storeHeader (_http_outgoing.js:222:9)
    at ServerResponse.writeHead (_http_server.js:214:8)
    at Server.<anonymous> (/home/dextor/Desktop/tailor-master/example/fragment.js:34:22)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:528:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)

npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "example"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! node-tailor@0.2.7 example: `npm run prepublish && node --harmony example/tailor`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-tailor@0.2.7 example script 'npm run prepublish && node --harmony example/tailor'.
npm ERR! This is most likely a problem with the node-tailor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run prepublish && node --harmony example/tailor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-tailor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-tailor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dextor/Desktop/tailor-master/npm-debug.log

I have installed all dependencies locally.

**Comment by vigneshshanmugam** [comment]
Thanks for letting us know. 

Addressed here - https://github.com/zalando/tailor/pull/42
