### ISSUE TITLE
production-level examples

### ISSUE THREAD

**Issue by timsim00** [zalando/tailor#40]
Love this repo.  Are there any production-level examples out there somewhere?

**Comment by lmineiro** [comment]
You mean some references of companies running this in production?

**Comment by timsim00** [comment]
I mean some open-source examples in addition to the basic example in this repo; to highlight some of the nuances of running this in a production setting.  (Kramer is awesome.)

**Comment by danpersa** [comment]
I'd say that there is nothing missing from examples in the repo. What you would do for your own app would be having more fragments (deployed on different machines) and more templates.

If you have many templates, you'd want a way to manage them (this is not in the scope of tailor).

**Comment by lmineiro** [comment]
Not as far as I know, unfortunately.

There are some nuances in the Zalando production environment. Some of them are:
- Custom logging and metrics
- Clustering (multiple processes to be able to use multiple CPUs)
- Circuit breakers (to access fragments and the template repository) and custom error handling 
- Caching
