### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by akeelnazir** [zalando/tailor#55]
Exception:
--------------
~/code/tailor/tailor-src$ npm run example

> node-tailor@1.0.1 example /Users/akeelnazir/code/tailor/tailor-src
> npm run prepublish && node --harmony example/tailor

> node-tailor@1.0.1 prepublish /Users/akeelnazir/code/tailor/tailor-src
> uglifyjs src/pipe.js --mangle --compress --comments -o src/pipe.min.js

Tailor started at port 8080
Fragment1 started at port 8081
Fragment2 started at port 8082
Fragment3 started at port 8083
fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/akeelnazir/code/tailor/tailor-src/example/templates/.html'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at /Users/akeelnazir/code/tailor/tailor-src/lib/fetch-template.js:11:31
    at Tailor.processRequest (/Users/akeelnazir/code/tailor/tailor-src/lib/request-handler.js:24:29)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)

filename: npm-debug.log
--------------
0 info it worked if it ends with ok
1 verbose cli [ '/Users/akeelnazir/n/bin/node',
1 verbose cli   '/Users/akeelnazir/n/bin/npm',
1 verbose cli   'run',
1 verbose cli   'example' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 verbose run-script [ 'preexample', 'example', 'postexample' ]
5 info lifecycle node-tailor@1.0.1~preexample: node-tailor@1.0.1
6 silly lifecycle node-tailor@1.0.1~preexample: no script for preexample, continuing
7 info lifecycle node-tailor@1.0.1~example: node-tailor@1.0.1
8 verbose lifecycle node-tailor@1.0.1~example: unsafe-perm in lifecycle true
9 verbose lifecycle node-tailor@1.0.1~example: PATH: /Users/akeelnazir/n/lib/node_modules/npm/bin/node-gyp-bin:/Users/akeelnazir/code/tailor/tailor-src/node_modules/.bin:/Users/akeelnazir/n/bin:/Users/akeelnazir/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/akeelnazir/n/bin:/Users/akeelnazir/kubernetes/cluster
10 verbose lifecycle node-tailor@1.0.1~example: CWD: /Users/akeelnazir/code/tailor/tailor-src
11 silly lifecycle node-tailor@1.0.1~example: Args: [ '-c', 'npm run prepublish && node --harmony example/tailor' ]
12 silly lifecycle node-tailor@1.0.1~example: Returned: code: 1  signal: null
13 info lifecycle node-tailor@1.0.1~example: Failed to exec example script
14 verbose stack Error: node-tailor@1.0.1 example: `npm run prepublish && node --harmony example/tailor`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/akeelnazir/n/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/akeelnazir/n/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid node-tailor@1.0.1
16 verbose cwd /Users/akeelnazir/code/tailor/tailor-src
17 error Darwin 15.6.0
18 error argv "/Users/akeelnazir/n/bin/node" "/Users/akeelnazir/n/bin/npm" "run" "example"
19 error node v6.2.1
20 error npm  v3.9.3
21 error code ELIFECYCLE
22 error node-tailor@1.0.1 example: `npm run prepublish && node --harmony example/tailor`
22 error Exit status 1
23 error Failed at the node-tailor@1.0.1 example script 'npm run prepublish && node --harmony example/tailor'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the node-tailor package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run prepublish && node --harmony example/tailor
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs node-tailor
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls node-tailor
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by vigneshshanmugam** [comment]
Once you start the example using `npm run example`. you need to open http://localhost:8080/index

Check [readme](https://github.com/zalando/tailor#example)
