### ISSUE TITLE
default template fetching reports template not found even when it is a different issue

### ISSUE THREAD

**Issue by aryszka** [zalando/tailor#70]
the error handling could use the err.code property to check if it is not found, or there is a different reason. In case of not found, the hosting app can choose to return 404, and e.g. 500 otherwise. Even better, it would be probably nicer if the promise was simply rejected with an error, wrapping the original error.

**Comment by aryszka** [comment]
probably the advice to #69 applies here, too?

**Comment by vigneshshanmugam** [comment]
landed in https://github.com/zalando/tailor/pull/71
