### ISSUE TITLE
Required fragments

### ISSUE THREAD

**Issue by StyleT** [zalando/tailor#79]
Hi!
Is there any way to mark some fragments as "required" so if they return error code we should return some general error page instead of broken one? This can be useful in case we want to show "Server error page" if server that server our header & footer is unavailable.

P.S.: It this behaviour makes sense for you guys I can help with a PR.

**Comment by vigneshshanmugam** [comment]
@StyleT Yeah its totally possible and you can mark the fragment that you want to control the status code of the page as `primary`

```html
<fragment primary src="url.com"></fragment>
```

**Comment by vigneshshanmugam** [comment]
and if you want to control the fragment fallback then you can also give the `fallback-src` if its down.

**Comment by StyleT** [comment]
@vigneshshanmugam problem here that header & footer fragments are not actually `primary` fragments. `primary` one in this theoretical setup with header, body & footer fragments is actually a `body`. 

And I can't use few primary fragments on the page.

Talking about `fallback-src`. Great feature, but what if fallback is also broken?

**Comment by vigneshshanmugam** [comment]
This Should clarify the overall idea..
+ There can be only one primary fargment on the page..  (If you have multiple the first one wins)
+ Primary decides the status code.. if `primary` fragment is down and doesn't have a `fallback-src` then 500 status code is returned and none of the fragments are rendered. 
+ If `primary` fragment is down and it does have a `fallback-src` then page will be rendered with 500 status code and fallback is fetched
+ If fallback is also down then status code will be still 500.. but the response is ignored.. all the other fragments are rendered as well.

**Comment by StyleT** [comment]
@vigneshshanmugam yep, got it. 
But what if I want to mark some fragments in such way so if some of them (and their fallbacks too) are down we should return some general error page instead of broken one?

**Comment by vigneshshanmugam** [comment]
@StyleT Hmm we haven't had/thought about this case.. Because we always serve the `fallback-src` from a CDN ( static error html)..

Doing the proposal that you are aiming for would require lots of bookkeeping and will need some tweaks in the way we compose streams!..

**Comment by w0rm** [comment]
Having the fallback of the fallback doesn't make sense to me..

**Comment by vigneshshanmugam** [comment]
I agree with @w0rm on this and in the end you would need to fall back to a page when your primary/required fragment is not available which is already solved in tailor. 

Having required is not in scope for now, Hence closing the issue
