### ISSUE TITLE
Node Engine version incorrect

### ISSUE THREAD

**Issue by SimeonC** [zalando/tailor#87]
I found that if you run tailor with the node engine version defined in the package (>4.4.X) you get the following error: `SyntaxError: Unexpected token ...` on this line: `fragment.on(eventName, (...args) => {`.

My colleague is running node 6.9.0 and that works fine, I am running 4.4.3 which doesn't work.

**Comment by rikkert** [comment]
Because tailor uses ES6 features you have to run with the --harmony parameter on your version of node. https://nodejs.org/en/docs/es6/

**Comment by vigneshshanmugam** [comment]
@SimeonC tailor uses es6 features and you need harmony flag on node 4.4.x versions. 

@rikkert Thanks!.

**Comment by SimeonC** [comment]
Hi, thanks for the info - sorry I didn't respond earlier!
