### ISSUE TITLE
Use with node-http-proxy

### ISSUE THREAD

**Issue by srcnix** [zalando/tailor#88]
Could someone give me an example of how to use a streaming response from node-http-proxy as a template input?

My templates come through node-http-proxy and I ideally need to then pipe this response through to tailor - any thoughts welcomed!

**Comment by rikkert** [comment]
You are doing this in the fetchTemplate right?

**Comment by srcnix** [comment]
@rikkert, currently, yes. However, I'm receiving an error stating that headers can no longer be modified as they have already been sent - which I am assuming node-http-proxy has done. 

I'm wondering if it's possible to apply Tailor to just before node-http-proxy streams the response.

**Comment by vigneshshanmugam** [comment]
@srcnix Sorry for the delay...was in vacation. Can you point me to an example repo or gist? I will play with it and let you know.

**Comment by srcnix** [comment]
@vigneshshanmugam, I actually managed to get this working. node-http-proxy ends a response itself, so I had to override the response on 'end' event.
