### ISSUE TITLE
Custom Require variable

### ISSUE THREAD

**Issue by SimeonC** [zalando/tailor#89]
I'm currently using tailor with webpack which means I'm not using require as it's supposed to work. Basically, I'm just using it to load the file if it isn't already loaded. My problem is that the "require" variable is causing conflicts. Would it be possible to have an option to change the "require" variable here: https://github.com/zalando/tailor/blob/ffe52cafe0a5b47daf4ad773037e8b9fae5d54e2/index.js#L34

I've replaced the line with: `return new Buffer(memoizedDefinition + `${pipeInstanceName} = new Pipe(${options.amdLoaderName || 'require'})</script>\n`);`

My amd loader file for reference:

```
(function (window, undefined) {
	let loaded = {};
	function loadModule(src, el) {
        // need to add new script to the browser
        el = window.document.createElement('script');
        el.src = src;
        window.document.head.appendChild(el);
    }
    
	function req(dependencyNames) {
		if (!loaded[dependencyNames[0]]) {
			loaded[dependencyNames[0]] = true;
			loadModule(dependencyNames[0]);
		}
    }
	window['tailor_require'] = req;
}(this));
```

**Comment by vigneshshanmugam** [comment]
@SimeonC Sorry for the delay. missed this issue. 

I got your concern. But you could totally send your own AMD loader which satisfies the API of require.js

Check this example on how you can modify the same here https://github.com/zalando/tailor/blob/master/examples/multiple-fragments-with-custom-amd/index.js#L10

**Comment by SimeonC** [comment]
No problems, thanks for getting back to me. I did this while trying to workaround using React and Webpack and thought it was conflicting with hot-loading js files - I later realised that webpack doesn't use the `window.require` variable anyway so it's not really an issue.

I guess thinking back what I was trying to do probably was going to cause even more issues than it solved.
