### ISSUE TITLE
Link tech blog articles and conference videos related to Skipper in the readme

### ISSUE THREAD

**Issue by jukey** [zalando/tailor#98]
### Idea

1. In order to give people a bit more background why Tailor exists and what alternatives where considered it would be great to link this blog article in the README.md:

   - [Better streaming layouts for front-end microservices with Tailor](https://www.oreilly.com/ideas/better-streaming-layouts-for-frontend-microservices-with-tailor)

2. Are there also some conference talks related to Tailor available we could show?

### Motivation

I got the feedback from people that are checking the projects on [Zalando github overview page](http://zalando.github.io/) that it's hard to get the context of projects. This could help these people to understand the purpose of this project better.

What do you think, @vigneshshanmugam ?

**Comment by vigneshshanmugam** [comment]
@jukey The blog post is already linked in https://github.com/zalando/tailor/blob/master/README.md and even the www.mosaic9.org
